### PR TITLE
design(TextInput): final design review for TextInput component

### LINKED ISSUE #239: [Task] Verify TextInput Component
Verify TextInput component to be used in the component library

## Context
_See_ https://cfpb.github.io/design-system/components/text-inputs

### Verify the CFPB Design System (React) component against the CFPB Design System
- [x] Has component intro text copied from the DS page
- [x] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [x] Each DS variant is implemented as a separate story
  - [x] Story name should be sentence case (ex. List Link => List link)
  - [x] Naming is consistent with the DS
  - [x] Same component names, same placeholder text, etc.
- [x] Order of stories matches between DS/DSR
- [x] Component is built correctly
  - [x] Visually compare DSR implementation to DS
  - [x] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [x] Manual visual review has been conducted and component has passed this review

~~#### For new components~~ 
~~- [ ] All steps for existing components plus the following steps~~
~~- [ ] The new component has been added to the CFPB Design System OR~~
~~- [ ] The CFPB Design System maintainers have been alerted that there is a new component that must be added to the system~~
~~- [ ] Documentation has been written for the new component (this is not a blocker for moving a component to verified)~~

### Run accessibility checks 
- [x] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [x] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
- [x] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [ ] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [ ] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [ ] Does the component have similar screen reader behavior as the sample components in WCAG, the CFPB design system, WebAIM, or similar accessibility examples?
- [x] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [x] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)
  
### Conduct PR review
- [x] The component has been reviewed and approved by UI, UX, and FEWD

### Verify component
- [x] Move component to verified in Storybook

### PR DESCRIPTION
**Pull request by shindigira**
closes #239 

The TextInput component was already dev verified https://github.com/cfpb/design-system-react/issues/239. 

# Final Design Review of TextInput Component
Verify TextInput component to be used in the component library
Link: https://deploy-preview-279--cfpb-design-system-react.netlify.app/?path=/docs/components-verified-text-inputs--overview

## Context
_See_ https://cfpb.github.io/design-system/components/text-inputs

### Verify the CFPB Design System (React) component against the CFPB Design System
- [x] Has component intro text copied from the DS page
- [x] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [x] Each DS variant is implemented as a separate story
  - [x] Story name should be sentence case (ex. List Link => List link)
  - [x] Naming is consistent with the DS
  - [x] Same component names, same placeholder text, etc.
- [x] Order of stories matches between DS/DSR
- [x] Component is built correctly
  - [x] Visually compare DSR implementation to DS
  - [x] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [x] Manual visual review has been conducted and component has passed this review

~~#### For new components~~ 
~~- [ ] All steps for existing components plus the following steps~~
~~- [ ] The new component has been added to the CFPB Design System OR~~
~~- [ ] The CFPB Design System maintainers have been alerted that there is a new component that must be added to the system~~
~~- [ ] Documentation has been written for the new component (this is not a blocker for moving a component to verified)~~

### Run accessibility checks 
- [x] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [x] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
- [x] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [x] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [x] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [x] Does the component have similar screen reader behavior as the sample components in WCAG, the CFPB design system, WebAIM, or similar accessibility examples?
- [x] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [x] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)
  
### Conduct PR review
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

### Verify component
- [ ] Move component to verified in Storybook

### CODE REVIEW

**Review by meissadia — APPROVED** [review]

**Comment by billhimmelsbach** [comment]
Heyo! Did Natalia already look at this to get it verified?

**Review by billhimmelsbach — CHANGES_REQUESTED** [review]
Heyo! I don't think @natalia-fitzgerald has seen this for design review. If you think it is ready for design review, could you follow [the verification steps over here](https://github.com/cfpb/design-system-react/issues/198#:~:text=Conduct%20Design%20PR,Mattermost%20when%20ready)?

**Comment by natalia-fitzgerald** [comment]
@shindigira 
How would you like me to approach the verification of this component? We have pending DS changes to the hover colors for the different status states. Should we complete those changes before or after verifying? 

In the DSR we show the different states for the standard text input as individual stories. For the status (Success, Warning, Error) we don't include stories for the states (Default, Hover, Focus). Should we include stories for these states?

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@shindigira 
This is looking great! I have a few structural changes and then we should be good to go.  

As we discussed I'd like to group this component as follows: 

Sidebar: 
- **Checkboxes**
  - Checkbox
    - Overview
    - Enabled
    - Hover
    - Focus
    - Selected
    - Disabled
    - Disabled/selected
    - Success
    - Warning
    - Error
    - With helper text
  - Large target area
    - Overview
    - Enabled
    - Hover
    - Focus
    - Selected
    - Disabled
    - Disabled/selected
    - With helper text
    
- Change "Default" to "Enabled" for the base state
- In helper text examples change the label text to "Label"
- Make status states interactive on the page

**Comment by natalia-fitzgerald** [comment]
@shindigira 

As we discussed I'd like to group this component as follows: 

Sidebar menu text:
**Text inputs**
- Overview
- Enabled
- Hover
- Focus
- Disabled
- Success
- Warning
- Error
- Full width
- With button
- Button inside
- Button inside (with button)

For Text area input, we discussed making it a separate component in the DSR. Can we do that as a part of this? Does the DS include state styling for Text area input? It's not visualized on the DS page but if it's in the code I'd like to pull it out/itemize it in the DSR.

**Comment by natalia-fitzgerald** [comment]
@shindigira 
This looks good. 

@billhimmelsbach or @meissadia what are your thoughts on making Text area a separate component in the DSR? Text input and Text area input both live under "Text inputs" (same page) in the DS.  If we decide to do that we can go ahead and open a ticket since this will be needed for the forms work we will likely be doing.

**Review by natalia-fitzgerald — COMMENTED** [review]
@shindigira
This looks good. Nice work!

**Review by natalia-fitzgerald — APPROVED** [review]

**Pull request merged**
