### PR TITLE
TextIntroduction -- Functional Dot Notation

### LINKED ISSUE #260: Reformat: TextIntroduction to use the 'functional dot notation'
Reformat to use a [functional dot notation](https://stackoverflow.com/questions/60882627/using-dot-notation-with-functional-component) method

## Current behavior

Screenshot 2023-11-29 at 10 25 22 AM

## Expected behavior

Screenshot 2023-11-29 at 5 54 51 PM

### PR DESCRIPTION
**Pull request by shindigira**
Closes #260 

## Changes

- TextIntroduction is now more composable with subcomponents
- TextIntroduction story is updated (click on See Code)

## How to test this PR

1. View TextIntroduction Storybook story
2. Code Inspection
3. `yarn test TextIntroduction`

## Screenshots
Screenshot 2023-12-05 at 9 56 55 AM

-

### CODE REVIEW

**Review by meissadia — COMMENTED** [review]
Seeing it built out, this design feels way more verbose than the original - both in implementation and in usage. 
 
If the goal is to avoid long inline string params, then that seems like a pattern we should practice (i.e. Define long string params as variables, do not create them inline when calling a component), similar to how you refactored `subheading` and `description`.  
 
I also find myself asking: *When* should a prop be implemented as a subcomponent?  Here you've kept `callToAction` as an inline prop.  Is that because the values we expect to be passed here should be relatively short? 
 
I'd like us to ponder this pattern a bit more before we make it a standard.

**Comment by meissadia** [comment]
Also, if we decide to move forward with this, please update the unit tests.

**Comment by meissadia** [comment]
I feel like there are more negatives than positives here:
- 280 more characters to achieve the same ouput
- More tags to visually parse in order to understand what is being rendered
- Requires dev to put elements in the correct order
- Allows devs to implement the pattern incorrectly

A big part of building this library is to codify the DS patterns in order to keep visual outputs aligned.  We've definitely built other escape hatches into our components that would allow devs to stray from the prescribed design but I'm not convinced the level of freedom or responsibility that this PR provides is what we want. 
 
Would be good to have a chat with @natalia-fitzgerald and @billhimmelsbach to explore the pros/cons.

**Comment by billhimmelsbach** [comment]
Heyo! Sorry @shindigira and @meissadia for the sick delay here. 🤒 I might have missed some context here while I was out, but did you have a use case @shindigira where you needed to compose these pieces of `TextIntroduction` for something on a page you were working on or is it that you thought this would just be a helpful refactor?

**Comment by billhimmelsbach** [comment]
> To begin with there is an _immediate use case_ from the Figma that breaks the component. One of said string props can no longer be a string prop; requires an actual component.

Could you point me to that Figma mockup?

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach @shindigira 
The "text introduction" is a specific component/pattern in the DS and should only be used in a limited number of ways. I did share some cf.gov outliers in last week's DSR meeting but these examples really no longer use the "text introduction" component (and decisions to break the component were specifically made by designers - not devs). For the sake of our component library we will want the component's design to push people to use it in the correct ways. So we should build in only the flexibility needed to accomplish the component's intent.

**Comment by billhimmelsbach** [comment]
Heyo! Just to recap our discussion @meissadia and @shindigira: we'll add an export to TextIntroduction that composes these subcomponents into one that shares the same props as the original TextIntroduction: strings and ReactNodes for parts of the component that require links. That way we'll get the best of both worlds: a more rigid component to enforce design standards built upon flexible, forward thinking subcomponents that we can use/compose for future use cases.

@shindigira will make sure that this new composed component meets his needs for his use case. 👍

**Comment by billhimmelsbach** [comment]
Great! Could you merge with `main` then I'll take a peek tomorrow. 👍

**Review by meissadia — APPROVED** [review]
👍🏾

**Review by billhimmelsbach — APPROVED** [review]
Heyo! Coming back around to give this a 👍. I also tried it out on `sbl-frontend` and it looks good. 🎉

**Pull request merged**
