### PR TITLE
design(Link): final design review for Link component

### LINKED ISSUE #215: [Task] Verify Links Component
Verify links component to be used in the component library

### Verify the CFPB Design System (React) component against the CFPB Design System
- [x] Has component intro text copied from the DS page
- [x] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [x] Each DS variant is implemented as a separate story
  - [x] Story name should be sentence case (ex. List Link => List link)
  - [x] Naming is consistent with the DS
  - [x] Same component names, same placeholder text, etc.
- [x] Order of stories matches between DS/DSR
- [x] Component is built correctly
  - [x] Visually compare DSR implementation to DS
  - [x] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [x] Manual visual review has been conducted and component has passed this review

### Run accessibility checks 
- [x] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [x] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
- [x] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [ ] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [x] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [ ] Does the component have similar screen reader behavior as the sample components in WCAG, WebAIM, or similar accessibility examples?
- [ ] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [x] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)
  
### Conduct PR review
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

### Verify component
- [ ] Move component to verified in Storybook

## Context
https://cfpb.github.io/design-system/components/links
Screenshot 2023-10-12 at 11 34 44 AM

### PR DESCRIPTION
**Pull request by meissadia**
Closes #215 
 
This PR is to get the Design team's (@natalia-fitzgerald) final approval. 

@billhimmelsbach @shindigira Please ignore

## Changes

- Moves Link component to Verified status

### Verify the CFPB Design System (React) component against the CFPB Design System
- [x] Has component intro text copied from the DS page
- [x] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [x] Each DS variant is implemented as a separate story
  - [x] Story name should be sentence case (ex. List Link => List link)
  - [x] Naming is consistent with the DS
  - [x] Same component names, same placeholder text, etc.
- [x] Order of stories matches between DS/DSR
- [x] Component is built correctly
  - [x] Visually compare DSR implementation to DS
  - [x] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [x] Manual visual review has been conducted and component has passed this review

### Run accessibility checks 
- [x] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [x] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
- [x] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [x] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [x] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [x] Does the component have similar screen reader behavior as the sample components in WCAG, the CFPB design system, WebAIM, or similar accessibility examples?
- [x] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [x] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)

### Conduct Code PR review
- [x] [Submit PR](https://github.com/cfpb/design-system-react/pull/207) with any necessary changes for code review by frontend devs and copy completed checklist above into PR description
  
### Conduct Design PR review
- [x] Prepare component to be reviewed and approved by UI/UX
  - [x] [Create a PR](https://github.com/cfpb/design-system-react/pull/218) with the name: `design(XXXX): final design review for XXXX component`
  - [x] Change [only component's](https://github.com/cfpb/design-system-react/pull/218/commits/f745c3c9043f9ab1e04c3150122d93b2df4e54a3) status from `Draft` to `Verified` in Storybook
  - [x] Apply GitHub label "[design](https://github.com/cfpb/design-system-react/labels/design)"
  - [x] Add @natalia-fitzgerald as additional reviewer
  - [x] Ping @natalia-fitzgerald on Mattermost when ready

### Verify component
- [ ] Merge when design review completed to finish component verification 🎉

### CODE REVIEW

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@meissadia 
The component is looking good! I made some text updates to the [CFPB Design System: Links](https://cfpb.github.io/design-system/components/links) page that I'd like to incorporate into the DSR page before we move to verified. 

**New intro text:** 
Links are navigational elements that connect users to other locations, either on the current page or to a different page or site. In contrast, [buttons](https://cfpb.github.io/design-system/components/buttons) are used to signal important actions.

**Stories**
- Inline link~~s~~
- List link ~~Call-to-action links~~
  - Change code example for the links to "List link 1" "List link 2"
- Destructive link~~s~~
  - Change code example link text to "Destructive link" (remove the word "Sample"
- Link with icon~~Standard link with icon~~
- Non-wrapping link with icon ~~icon links~~
- Jump link
  - Change code example for the link to "Jump link" (remove the word "Default")
- Jump link with icon on the left 
- Printed link~~s~~ (Should we add this to the DSR?)

**Comment by billhimmelsbach** [comment]
Just changed the title and added a label just to make it align [with these steps](https://github.com/cfpb/design-system-react/issues/198#:~:text=The%20component%20has,Mattermost%20when%20ready) I wrote up last week. We can discuss/change the steps if we want to, but just wanted to make the outstanding PRs consistent for now.

**Review by natalia-fitzgerald — APPROVED** [review]
Looks good!

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
- Change intro text to: 
Links are navigational elements that connect users to other locations, either on the current page or to a different page or site. In contrast, [buttons](https://cfpb.github.io/design-system/components/buttons) are used to signal important actions.

- Change "Call-to-action links" to "List links"
- Change live code text to: "List link 1" and "List link 2"
- Change "Sample destructive link" to "Destructive link" 
- Change "Standard link with icon" to "Link with icon"
- Change "Non-wrapping icon links" to "Non-wrapping link with icon"
-

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Also: Change "Default jump link" to "Jump link" - in the live code example

**Comment by natalia-fitzgerald** [comment]
The changes just made are the same ones I made here: https://github.com/cfpb/design-system-react/pull/228#pullrequestreview-1708595027

I also asked about whether we should include the "[Printed links](https://cfpb.github.io/design-system/components/links#printed-links)"

**Review by natalia-fitzgerald — APPROVED** [review]
Looks great!

**Pull request merged**
