### PR TITLE
design(banner): final design review for Banner (US gov)

### LINKED ISSUE #213: [Task] Verify Banner component
Verify banner component to be used in the component library

### Context
Depends on verification of the Tagline component: https://github.com/cfpb/design-system-react/issues/205
Screenshot 2023-10-12 at 11 30 15 AM

### Verify the CFPB Design System (React) component against the CFPB Design System
- [ ] Has component intro text copied from the DS page
- [ ] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [ ] Each DS variant is implemented as a separate story
  - [ ] Story name should be sentence case (ex. List Link => List link)
  - [ ] Naming is consistent with the DS
  - [ ] Same component names, same placeholder text, etc.
- [ ] Order of stories matches between DS/DSR
- [ ] Component is built correctly
  - [ ] Visually compare DSR implementation to DS
  - [ ] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [ ] Manual visual review has been conducted and component has passed this review

### Run accessibility checks 
- [ ] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
- [ ] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [ ] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [ ] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [ ] Does the component have similar screen reader behavior as the sample components in WCAG, WebAIM, or similar accessibility examples?
- [ ] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [ ] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)
  
### Conduct PR review
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

### Verify component
- [ ] Move component to verified in Storybook

### PR DESCRIPTION
**Pull request by billhimmelsbach**
Makes changes to Banner (US gov) to move to verified.
Screenshot 2023-11-21 at 11 26 43 AM

Note: Made the default tagline for the Banner (US gov) [match the text and markup](https://github.com/cfpb/design-system-react/pull/246/files#diff-f9882edc8324cf88b43076801e6c25a605f41b89e1e3bf19a04c7eb2c05619a7R40) of the banner displayed in the DS. This better matches the DS, and avoids having to remember to wrap the "United States government" part of the tagline in a span with class `u-nowrap` in the instances it occurs.

Closes #213 

### Verify the CFPB Design System (React) component against the CFPB Design System
- [x] Has component intro text copied from the DS page
- [x] Has source link to component's DS page (ex - Source: https://cfpb.github.io/design-system/components/banner-notification)
- [x] Each DS variant is implemented as a separate story
  **- Note: the design system only includes one use case without links, our examples in the DSR also include one with generic links and one with the implementation on cf.gov**
  - [x] Story name should be sentence case (ex. List Link => List link)
  - [x] Naming is consistent with the DS
  - [x] Same component names, same placeholder text, etc.
- [x] Order of stories matches between DS/DSR
- [x] Component is built correctly
  - [x] Visually compare DSR implementation to DS
  - [x] Verify that React renders the HTML markup the same as in the DS (if at all possible)
  - [x] Verify that DS classes (organisms, molecules, atoms) are used, as opposed to styles defined in DSR
- [x] Check to see if the applied CSS styles match the Specs in the DS if applicable (message @natalia-fitzgerald if it does not)
- [x] Manual visual review has been conducted and component has passed this review

#### ~For new components~
- ~[ ] All steps for existing components plus the following steps~
- ~[ ] The new component has been added to the CFPB Design System OR~
- ~[ ] The CFPB Design System maintainers have been alerted that there is a new component that must be added to the system~
- ~[ ] Documentation has been written for the new component (this is not a blocker for moving a component to verified)~

### Run accessibility checks 
- [x] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [x] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)
**Note: links don't go anywhere in the example, which is fine**
- [x] Component is screen reader friendly ([screen reader testing demo](https://drive.google.com/file/d/189A9Wx_T1C49TES5ZtYXlIFbJbLP472p/view))
  - [x] Is all the meaningful visual information and text of the component conveyed by the screen reader? (text, non-decorative image descriptions, etc.)
  - [x] When interacting with the component using a screen reader, do you have all the information you need to use it? (selected vs unselected, button vs link, expanded vs collapsed, etc.)
  - [x] Does the component have similar screen reader behavior as the sample components in WCAG, the CFPB design system, WebAIM, or similar accessibility examples?
- [x] For reference: [CFPB manual web accessibility audit](https://cfpb.github.io/design-system/guidelines/accessibility-audit-tools#cfpb-manual-web-accessibility-audit-1) 

### Verify component unit tests
- [x] Verify component unit tests are implemented and passing - 85% or greater (ex: `yarn vitest Button`)

### Conduct Code PR review
- [ ] [Submit PR](https://github.com/cfpb/design-system-react/pull/207) with any necessary changes for code review by frontend devs and copy completed checklist above into PR description
**I'm going to skip this step to get it front of Natalia**
  
### Conduct Design PR review
- [x] Prepare component to be reviewed and approved by UI/UX
  - [x] [Create a PR](https://github.com/cfpb/design-system-react/pull/218) with the name: `design(XXXX): final design review for XXXX component`
  - [x] Change [only component's](https://github.com/cfpb/design-system-react/pull/218/commits/f745c3c9043f9ab1e04c3150122d93b2df4e54a3) status from `Draft` to `Verified` in Storybook
  - [x] Apply GitHub label "[design](https://github.com/cfpb/design-system-react/labels/design)"
  - [x] Add @natalia-fitzgerald as additional reviewer
  - [x] Ping @natalia-fitzgerald on Mattermost when ready

### Verify component
- [ ] Merge when design review completed to finish component verification 🎉

### CODE REVIEW

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
Change: 
- US gov banner with generic links to US gov banner (with generic links)
- US gov banner with cf.gov links to US gov banner (cf.gov)- also put this one second in the list

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
US should be capitalized in the story names: 
- US gov banner
- US gov banner (cf.gov)
- US gov banner (with generic links)

**Comment by billhimmelsbach** [comment]
I'm guessing you mean in the sidebar?

Screenshot 2023-11-21 at 3 25 31 PM

**Comment by billhimmelsbach** [comment]
I adjusted the way sentence case is enforced in the sidebar @natalia-fitzgerald to make an exception for US initials. 👍

https://github.com/cfpb/design-system-react/blob/9fa26d370bbf177dc93fd8b846f7418bc22d25e0/.storybook/manager.js#L12-L13

**Review by natalia-fitzgerald — APPROVED** [review]
Nice work! Looks great.

**Review by meissadia — APPROVED** [review]
Looks good 👍🏾 
 
Odd that `<UnclickableLink>` components become `<o>` components in the code examples but not sure what is causing that.  
 
Screenshot 2023-11-22 at 9 40 44 AM

**Review by natalia-fitzgerald — APPROVED** [review]

**Pull request merged**
