### PR TITLE
[Component] Heading

### LINKED ISSUE #161: [Component] Headings (1-6)
# [Headings](https://cfpb.github.io/design-system/foundation/headings#web-headings)
Tracking the design and development lifecycle of the headings component.

### Related links: 
- **Design System (Documentation):** https://cfpb.github.io/design-system/foundation/headings#web-headings
- **Design System (Codebase):** https://github.com/cfpb/design-system

| Design System | 
|------------| 
|Screen Shot 2023-08-25 at 7 50 10 AM|
 
###  Checklist
- [X] The component has an identified use case (one of the 3 options below)
- [X] The current state of the component has been identified (one of the 3 options below)
- [X] The task is broken into steps

### Identify the use case: 
- [X] Small business lending filing platform 
  - Complete user profile page: Heading Text
- [ ] Metro 2 tool
- [ ] No identified project need but does exist in the CFPB Design System

### Identify the current state:
- [X] The component already exist in the CFPB Design System  
  - Build an exact React translation of the CFPB Design System component
  - Build the component in Figma (if it is not already included in the CFPB Design System template)

- [ ] The component does not exist in the CFPB Design System but does exist on cf.gov 
  - Conduct a design audit of any component variations that exist on our website (if applicable)
  - Determine final design
  - Build the component in Figma (if it is not already included in the CFPB Design System template)
  - Add the component to UI component library
  - Incorporate the component into the CFPB Design System or alert the CFPB Design System maintainers that this component will need to be added.

- [ ] The component does not exist in the CFPB Design System or on cf.gov (but has an identified use case and is being tracked as part of the SBL or M2 work)
  - Design the component as a part of the SBL or Metro 2 project work
  - Build the component in Figma (if it is not already included in the CFPB Design System template)
  - Add the component to UI component library
  - Incorporate the component into the CFPB Design System or alert the CFPB Design System maintainers that this component will need to be added.

#### Types
- [X] Headings (1-6)
- [ ] Variations: Heading with icon
- [ ] Variations: Eyebrow heading
- [ ] Variations: Slug heading

### Component is fully functional
- [ ] Visual regression testing has been conducted
- [ ] All interactive states are accounted for and incorporated 
- [ ] The component is successfully integrated into the Small business lending filing platform (or prototype) or other CFPB  web app

### Accessibility checks have been completed
- [ ] Component is keyboard-friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Component is screen reader friendly
- [ ] Component does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

### For existing Design System components: 
- [ ] React component visually and functionally matches the CFPB Design System component 
- [ ] Visual regression testing has been conducted and component has passed all tests
- [ ] Manual visual review has been conducted and component has passed this review
- [ ] Storybook page includes all types and variations of the component that are included in the CFPB Design System

### For new components: 
- [ ] The CFPB Design System maintainers have been alerted that there is a new component that must be added to the system OR
- [ ] We have added the new components to the CFPB Design System
- [ ] Documentation has been written and is included in Storybook and/or the CFPB Design System

### Final sign off
- [ ] The component has been reviewed and approved by UI, UX, and FEWD

### LINKED ISSUE #167: [Bug] Chromatic github action fails

### PR DESCRIPTION
**Pull request by meissadia**
Closes #161

## Changes

- feat: Ability to create `h1` - `h5` elements
- feat: Ability to create "Display heading"
- feat: Ability to create "Eyebrow heading"
- feat: Ability to create "Slug heading"
- feat: Icon w/ Text table on the Icons page

## How to test this PR

1. yarn vitest Heading

## Screenshots
Updated: Sept 29

### Sidebar
Screenshot 2023-09-29 at 9 24 38 AM

### Overview
screencapture-localhost-6006-2023-09-29-09_24_40

### Icons with Text ([live preview](https://deploy-preview-175--cfpb-design-system-react.netlify.app/?path=/docs/components-icon--overview#icon-with-text)) - (On the Iconography page)
Screenshot 2023-09-26 at 2 09 59 PM

## Notes
- I've excluded the `Heading with icon` variant as that was not targeted in #167 
- I did include `slug`, `eyebrow` and `super` because I hadn't realized these were not targeted in #167 until after they were already complete.

### CODE REVIEW

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Can we change the name of the "Superheading" to "Display"? I see in the DS this is labeled with a class of "superheading" but this is not the way we reference this heading ever. On the website and in print it is always referred to as "Display heading" or "Display." If we wanted to change this on the Design System side as well how disruptive do you think that would be?

**Comment by meissadia** [comment]
@natalia-fitzgerald 

> Can we change the name of the "Superheading" to "Display"?

Done ✅ 

> If we wanted to change this on the Design System side as well how disruptive do you think that would be?

Assuming this would be changing the classname from "superheading" to "displayheading" or similar? It seems like a small change in the DS as there are only two places that reference "superheading".  
 
As for the downstream implications, replacing the "superheading" class would break styles for any apps that rely on it.  Since it would be a breaking change this would require a new major version release of the DS library.  
  
Alternatively we could start a transition phase by duplicating the "superheading" styles as "displayheading", updating the DS docs page to prefer to the new classname, and maybe add a warning that the "superheading" class will be deprecated in future versions of the DS.

**Comment by natalia-fitzgerald** [comment]
@meissadia - Since “Heading with icon” is included on the Design System page for “Headings” we should consider including it here. Or do we currently include it somewhere else in the Storybook library? In the CFPB Design System we include “Heading with icon” on both the “Headings” page and on the “Iconography” page.

**Comment by meissadia** [comment]
> Since “Heading with icon” is included on the Design System page for “Headings” we should consider including it here. Or do we currently include it somewhere else in the Storybook library? In the CFPB Design System we include “Heading with icon” on both the “Headings” page and on the “Iconography” page.

Can do.  I think it would stay in the "Headings" section since it's a variation on how the heading element is composed.  And I don't see it on the [Iconography](https://cfpb.github.io/design-system/foundation/iconography). 
 
I do see the [Icons with text](https://cfpb.github.io/design-system/foundation/iconography#icons-with-text-1) section, which could be implemented as it's own component and could help solve the [Consistent Icon/Text spacing issue](https://github.com/cfpb/design-system-react/issues/130).  
 
 Question: Should our implementation be the whole meta header or just the "heading" (that is implemented in the DS as an anchor element) that includes an icon?

**Comment by meissadia** [comment]
- Still discussing if we should include `Heading w/ Icon` or if that should be saved for a future MetaHeader component
- Only h1-h6 were requested in original issue, should we remove Slug & Eyebrow?

**Review by natalia-fitzgerald — COMMENTED** [review]
@meissadia 
We should include the Eyebrow and the Slug since they are standard components and could come up as we build out more pages for SBL. The Slug is mainly used for sidebar content headings. We could handle Icons + Text as a separate PR if you'd like. I would like to discuss that one in more detail but I don't want to hold up the rest of this PR.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
I read through the “Heading with icon” content on the CFPB Design System and I think that it refers only to that specific implementation that typically appears within the results of a filterable list. I think that the CFPB Design System name for this component should be changed to something more specific, because “Heading with text” is more aligned with what we currently refer to as “Icons with text.” Next week I’ll post a CFPB DS issue to change the name of this component within the Design System. 

In terms of whether we should add it to the React component library now I’d say that we should but hold off until after we have the naming discussion in the DS repo. Or we can wait for a known use case in the SBL app. Whichever of these things happens first.

**Comment by meissadia** [comment]
Per conversation with Natalia this a.m.:
- We're holding off on implementing the `Heading with icon` variant
- I've verified that Headings sizes adjust (shift to a smaller font-size) on at mobile device widths
- Screenshots in PR description are up-to-date

**Comment by natalia-fitzgerald** [comment]
@meissadia 
- Change "Heading level 1" to "Heading 1" and make this change globally to all heading levels.
- Change "Display heading" to "Display"

**Review by natalia-fitzgerald — APPROVED** [review]
@meissadia - I left some comments in a separate post. Just minor content edits.

**Comment by meissadia** [comment]
> @meissadia
> 
> * Change "Heading level 1" to "Heading 1" and make this change globally to all heading levels.
> * Change "Display heading" to "Display"

@natalia-fitzgerald 

Updated:

## Sidebar
Screenshot 2023-09-28 at 1 49 56 PM

## Stories
screencapture-localhost-6006-2023-09-28-13_52_04

**Comment by natalia-fitzgerald** [comment]
@meissadia 
The content changes look good!

**Comment by natalia-fitzgerald** [comment]
@meissadia 
There is one more change to the headings page. Please remove the H6 from the type hierarchy. This is being deprecated from the CFPB DS and should not be used here.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Moving this from our chat convo: For Headings, change the example to show Heading 1 instead of Display. It is fine to move Display out of the first position to make this possible.

**Pull request merged**
