### PR TITLE
Better align Checkboxes documentation with Design System 

### LINKED ISSUE #168: [Component] Checkboxes
- [x] Change Storybook name from Checkbox -> Checkboxes
- [x] Language: Standard checkboxs -> Standard checkbox
- [x] Language: Standard checkbox states -> States
- [x] Style: Paragraph font to 16px
- [x] Style: Paragraph width to 670px
- [x] Language: Default checkbox -> Checkbox
- [x] Language: Sentence case with all labels (in stories)
  - ex: Checkbox With Helper
- [x] Large target - Remove intro paragraph
- [x] Reorg: Move `Checkbox with helper` down below somewhere

### PR DESCRIPTION
**Pull request by meissadia**
Closes #168

## Changes

- Change Storybook name from Checkbox -> Checkboxes
- Language: Standard checkboxs -> Standard checkbox
- Style: Intro Paragraph font to 16px
- Language: Sentence case with all labels (in stories)
- Large target - Remove intro paragraph
- Reorg: Move `Checkbox with helper` down below somewhere

## How to test this PR

1. Visit the [Netlify preview](https://deploy-preview-170--cfpb-design-system-react.netlify.app/?path=/docs/components-checkboxes--overview)
1. Confirm that the page flow feels sensible

## Screenshots
Updated: Sept 29

### Sidebar
Screenshot 2023-09-29 at 1 06 08 PM

### Overview
screencapture-localhost-6006-2023-09-29-15_54_15

### CODE REVIEW

**Comment by natalia-fitzgerald** [comment]
@meissadia 
- Change intro text to: "Use checkboxes when the user can select more than one option from a list. Make clear with helper text that this is the case. Use [radio buttons](https://cfpb.github.io/design-system/components/radio-buttons) when the user can choose only one option from a list." (I recently made this edit to the Design System documentation)
- For consistency between the types, change "Large target area checkboxes" to "Large target area checkbox" 
- For "Checkbox with helper text" change the first one to "Standard checkbox" and the second one to "Large target area checkbox"
- Change "Design System" to "CFPB Design System"

For discussion: 
- What do you think of "CFPB Design System documentation" instead of "CFPB Design System guidance"? I also like guidelines but I also see that that is a section name so we can't use it to refer to the whole collection of things documented in the DS. 

The VA takes this approach: 
[View guidance for the Date component in the Design System](https://design.va.gov/components/form/date-input)  

Screenshot 2023-09-13 at 2 09 02 PM


USWDS takes this approach: 
Source: https://designsystem.digital.gov/components/checkbox
Screenshot 2023-09-13 at 2 09 45 PM

**Comment by meissadia** [comment]
@natalia-fitzgerald 

> * What do you think of "CFPB Design System documentation"

I like it to avoid conflicts.
 
> Re: how others link to DS source

I like my experiment of matching the DS' content links from the page heading because it helps inform Storybook users about what additional info they can find in the DS docs, but it is a slight pain in the neck to recreate in Storybook.
 
Between the  VA / USWDS approaches - I like the simplicity of USWDS (no icon) but would prefer something more descriptive than just `Source`.  
 
How about "Additional documentation: link-to-docs"?  Just "Documentation" feels odd since Storybook is a form of documentation.  
Screenshot 2023-09-14 at 1 51 41 PM

**Comment by natalia-fitzgerald** [comment]
### Brainstorming the text that links to CFPB Design System

- Additional guidelines: https://cfpb.github.io/design-system/components/checkboxes
- Additional guidance: https://cfpb.github.io/design-system/components/checkboxes
- Usage guidelines: https://cfpb.github.io/design-system/components/checkboxes
- https://cfpb.github.io/design-system/components/checkboxes
- CFPB Design System: https://cfpb.github.io/design-system/components/checkboxes
- CFPB Design System Guidelines: https://cfpb.github.io/design-system/components/checkboxes
- For additional guidelines visit https://cfpb.github.io/design-system/components/checkboxes
- For behavior, usage, and accessibility guidelines visit https://cfpb.github.io/design-system/components/checkboxes

**Comment by meissadia** [comment]
> ### Brainstorming the text that links to CFPB Design System
> * https://cfpb.github.io/design-system/components/checkboxes
> * Additional guidelines: https://cfpb.github.io/design-system/components/checkboxes
> * Additional guidance: https://cfpb.github.io/design-system/components/checkboxes
> * Usage guidelines: https://cfpb.github.io/design-system/components/checkboxes
> * CFPB Design System: https://cfpb.github.io/design-system/components/checkboxes
> * CFPB Design System guidelines: https://cfpb.github.io/design-system/components/checkboxes
> * For additional guidelines visit https://cfpb.github.io/design-system/components/checkboxes
> * For behavior, usage, and accessibility guidelines visit https://cfpb.github.io/design-system/components/checkboxes
> * For usage guidelines visit https://cfpb.github.io/design-system/components/checkboxes

@natalia-fitzgerald I like these two the best. They feel like they better convey that there is more detailed information about the component available.  I would vote for option 2 because it's the most explicit about what they *could* find by following the link. 
1. For additional guidelines visit https://cfpb.github.io/design-system/components/checkboxes
1. For behavior, usage, and accessibility guidelines visit https://cfpb.github.io/design-system/components/checkboxes
 
...but maybe I'm just under estimating how effective a simple `Source: <link>` would be.  If a Storybook visitor went through our page and didn't find what they were looking for, the `Source: <link>` would be a logical place to continue their search - thus succinctly achieving our goal.  
 
 Maybe simple is best?

**Comment by natalia-fitzgerald** [comment]
@meissadia - Can you post a screenshot of where we are now with this page?

**Comment by meissadia** [comment]
> Can you post a screenshot of where we are now with this page? Have these changes been incorporated in the screenshot? [#170 (comment)](https://github.com/cfpb/design-system-react/pull/170#issuecomment-1718094139)

Thanks for the reminder.  Updated screenshot here and above. 
 
 I've gone back to just the `Source: ...` approach.  
screencapture-localhost-6006-2023-09-20-09_46_21

**Comment by meissadia** [comment]
[Experiment with removing the customized docs and relying on the DS for the more detailed explanation ](https://deploy-preview-170--cfpb-design-system-react.netlify.app/?path=/docs/components-checkboxes--overview)

screencapture-localhost-6006-2023-09-21-16_03_08

**Comment by meissadia** [comment]
Per conversation with Natalia this a.m., the following have been implemented:
- Updated story names to sentence-case
- Updated story order
- Going with the `Source: <link>` style of connecting the DS documentation

**Review by natalia-fitzgerald — COMMENTED** [review]
@meissadia 
For consistency, change "Checkbox with helper text" to "Standard checkbox with helper text"

**Review by natalia-fitzgerald — COMMENTED** [review]
@meissadia 
This is looking great. I have just a couple small content tweaks. 

Change both instances of helper text to: 
(This is optional helper text)
- This block must be in parenthesis according to the content guidelines. 

Screenshot 2023-09-29 at 4 38 06 PM
Screenshot 2023-09-29 at 4 38 11 PM

- Can you confirm the styling for the Checkbox label and the helper text? I think that we may be missing a CFPB DS update that fixed the styling of the helper text (size and color).

**Comment by meissadia** [comment]
@natalia-fitzgerald Updated to include:
- Helper text in perenthesis
- Upgraded CFPB DS to v0.31 to incorporate latest changes

[Live preview deployment](https://deploy-preview-170--cfpb-design-system-react.netlify.app/?path=/docs/components-checkboxes--overview)

screencapture-localhost-6006-2023-09-29-15_54_15

**Review by natalia-fitzgerald — APPROVED** [review]
Looks great!

Approved with one content change:
- Change text in both instances of helper text to:
(This is optional helper text)

**Pull request merged**
