### PR TITLE
Add tests to the `Link` component

### LINKED ISSUE #222: [Task] Create Tests for List Component
The [List component](https://cfpb.github.io/design-system-react/?path=/docs/components-draft-lists--overview) doesn't have tests written for it yet, and it would be great to establish some basic tests to check that it renders correctly. I'm imagining 5 test cases to start based on the code below:

https://github.com/cfpb/design-system-react/blob/c0678a225b93d114ca24c5f914d5f391dc2865a9/src/components/List/List.tsx#L22-L28

This issue would be completed if the following tests are written:

1. `m-list__horizontal` class is added to `List` when `isHorizontal` prop is passed in
2. `m-list__links` class is added to `List` when `isLinks` prop is passed in
3. `m-list__spaced` class is added to `List` when `isSpaced` prop is passed in
4. `m-list__unstyled` class is added to `List` when `isUnstyled` prop is passed in

5. `<ol>` list is rendered when `isOrdered` prop is passed in

Add these 5 render tests into a file called `List.test.tsx` in the same folder as `List.tsx`.

The tests could look very similar to other basic rendering tests in the codebase like [these label tests](https://github.com/cfpb/design-system-react/blob/main/src/components/Label/Label.test.tsx#L17).

Let me know if you have any questions! 👍

### PR DESCRIPTION
**Pull request by alberturria**
Addition of unit tests to the `Link` component, in the same flavour as in [these other tests](https://github.com/cfpb/design-system-react/blob/main/src/components/Label/Label.test.tsx#L17)

## Changes

- Links.test.tsx => Addition of file with the tests supporting:
1. m-list__horizontal class is added to List when isHorizontal prop is passed in
2. m-list__links class is added to List when isLinks prop is passed in
3. m-list__spaced class is added to List when isSpaced prop is passed in
4. m-list__unstyled class is added to List when isUnstyled prop is passed in
5. <ol> list is rendered when isOrdered prop is passed in

## How to test this PR

1. Run `npm t Link.test.tsx`

## Screenshots
image

## Notes

closes #222

### CODE REVIEW

**Review by billhimmelsbach — APPROVED** [review]
Looks great! 👍 Thanks for your work @alberturria! You're good to merge in: the Chromatic visual regression test is only failing since you're not part of our org, so don't worry about that failing status check when you're merging.

Would you be interested in some more testing related PRs? Maybe something a little more involved/fun like some behavioral tests for a more complicated component? I'm happy to write up a new issue for you, and work with you if you have any questions.

Thanks again @alberturria! We appreciate your contribution, and let me know if you'd like to stay involved! 🎉

**Comment by alberturria** [comment]
> Looks great! 👍 Thanks for your work @alberturria! You're good to merge in: the Chromatic visual regression test is only failing since you're not part of our org, so don't worry about that failing status check when you're merging.
> 
> Would you be interested in some more testing related PRs? Maybe something a little more involved/fun like some behavioral tests for a more complicated component? I'm happy to write up a new issue for you, and work with you if you have any questions.
> 
> Thanks again @alberturria! We appreciate your contribution, and let me know if you'd like to stay involved! 🎉

Thank you @billhimmelsbach !
Definitively I would love to contribute on something else within this repo 🙂.
 Feel free to assign any other issue to me 💪 .

**Comment by alberturria** [comment]
Btw @billhimmelsbach feel free to merge this PR once the CI passes again :slightly_smiling_face: 
Sorry, but `main` got updated and I needed to update my base branch again (blocking me to actually merge this PR :cry: )

**Comment by billhimmelsbach** [comment]
Heyo! Will do @alberturria! I'm going to work up a more interesting ticket for you too soon. 👍

**Review by billhimmelsbach — APPROVED** [review]

**Pull request merged**
