### PR TITLE
Checkbox Sidemenu Updated, Checkbox States (Error/Warning/Success)

### LINKED ISSUE #285: [Checkbox] Define state styling (Success/Warning/Error status) - DSR
Implements https://github.com/cfpb/design-system/issues/1883

### LINKED ISSUE #286: [Checkbox][Table of Contents] Storybook Sidemenu Update
Update Checkbox Storybook tree menu to this format:

Screenshot 2024-01-25 at 11 24 43 PM

### PR DESCRIPTION
**Pull request by shindigira**
Closes #286 
Closes #285 

## Changes
- Checkbox - Storybook Sidemenu Update
- Styling: Checkbox States (Error/Warning/Success) 

### Sidemenu Updated

|Before|After|
|---|---|
|Screenshot 2024-01-23 at 12 52 25 PM|Screenshot 2024-01-29 at 11 21 59 AM|

### New Checkbox Status
Screenshot 2024-01-23 at 12 54 16 PM

### CODE REVIEW

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@shindigira 
This is looking great! I have a few structural changes and then we should be good to go.  

As we discussed I'd like to group this component as follows: 

Sidebar menu: 
- **Checkboxes**
  - Checkbox
    - Overview
    - Enabled
    - Hover
    - Focus
    - Selected
    - Disabled
    - Disabled/selected
    - Success
    - Warning
    - Error
    - With helper text
  - Large target area
    - Overview
    - Enabled
    - Hover
    - Focus
    - Selected
    - Disabled
    - Disabled/selected
    - With helper text

Additional changes:    
- Change "Default" to "Enabled" for the base state
- In helper text examples change the label text to "Label"

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@shindigira 
Nice work! Just a few details and we should be good to go: 

- Change "Default" to "Checkbox" 
- Is it possible for the page to read "Large target area checkbox" and still have the side menu read "Large target area"? This would match the DS.

**Review by natalia-fitzgerald — DISMISSED** [review]
@shindigira - Great work! This looks good and move to verified.

**Review by meissadia — DISMISSED** [review]
Awesome job finding ways to reconfigure in order to achieve the custom Overviews!

**Review by meissadia — APPROVED** [review]

**Pull request merged**
